version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: credilio_demo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  adonisjs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - APP_KEY=dTw9Lyepj8iLjR_Wh0q
      - DB_CONNECTION=pg
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=root
      - PG_PASSWORD=root
      - PG_DB_NAME=credilio_demo
    volumes:
      - .:/app
